### ISSUE TITLE
Change alias 24/7 (synonym for 00:00-24:00) to 24/1

### ISSUE THREAD

**Issue by ypid** [AMDmi3/opening_hours.js#13]
Currently 24/7 is accepted as synonym for 00:00-24:00. I kind of get it why you implemented it but I think it makes scene to change this to a more applying shortcut for example 24/1.

What do you think about it? I am still working on it: https://github.com/ypid/opening_hours.js/tree/feature

**Comment by AMDmi3** [comment]
I'm against it as it because it's unneeded extension for the schema and it doesn't accomplish anything 24/7 does not.

**Comment by ypid** [comment]
By now I am more on your side with the 24/7 alias, but I will probably never use it because it conflicts with my best practices of writing opening_hours.

**Comment by ypid** [comment]
I found another solution. We don’t have to invent a new token because it already exists … We can always use "open", "close" or "unknown" in case of 24/7. So the use of 24/7 as synonym for 00:00-24:00 is now deprecated and will return a warning.
I guess we should remove the extend line in https://github.com/ypid/opening_hours.js/tree/master#time-ranges

The test also includes "24/7; Mo 12:00-14:00 off" which can be expressed as "open; Mo 12:00-14:00 off".

My previous answer was based on the idea that there are no better and shorter keywords which is not true anymore (now that I implemented "open" and "closed").

**Comment by AMDmi3** [comment]
Open/close is an undocumented (they are not even mentioned on Key:opening_hours) extension and 24/7 is not deprecated. There should not be any warnings.

**Comment by ypid** [comment]
But it is used by now, and it is the better choice "24/7; Mo 12:00-14:00 off" -> "open; Mo 12:00-14:00 off" don’t you think?

24/7 is by no means deprecated, it is only not good practice to use it in a way that does not mean "24/7". This can be avoided. If open is not mentioned by Key:opening_hours then we should change that because it is necessary for comments which are used in around 1000 values.

The warning just says that this can be expressed in a more clear manner.

**Comment by AMDmi3** [comment]
Let's start from that it's totally undocumented.

**Comment by ypid** [comment]
If Netzwolf could put his specification back on then it is not. I guess no one wrote it in the wiki because it was on the homepage of Netzwolf.
They were documented (just a few days ago).

Lets assume it would be undocumented (which happens all the time in OSM): There are enough people who used it by now and it is worth supporting so I do it.
