### ISSUE TITLE
In some POI the script doesn't work

### ISSUE THREAD

**Issue by airon90** [AMDmi3/opening_hours.js#16]
[OSM24](http://osm24.eu) is a project that implements your Javascript library.

In some cases, opening_hour tag is set but o_h.js doesn't work: [Example](http://osm24.eu/index.php#!18/45.61184/8.84412/type=eat/)

**Comment by AMDmi3** [comment]
There's an error in data:

`Mo 18:00-22:00;Tu-Fr 11:30-16:00, 18:00-22:00;Sa 11:30-16:00, 18:00-23:00, Su off`
should be:
`Mo 18:00-22:00;Tu-Fr 11:30-16:00, 18:00-22:00;Sa 11:30-16:00, 18:00-23:00; Su off`

**Comment by airon90** [comment]
Ok thank you!
